# v11 - 피처 정리 + CB 3seed × 팀원 XGB 크로스 블렌딩
시각: 20260316_133331
============================================================

## [1] 데이터 로드
- train: (256351, 69), test: (90067, 68)
- 타겟: 0=190123, 1=66228, 양성비율=25.8%

============================================================
## PIPELINE A: CatBoost (피처 축소, 원본 카테고리 유지)
============================================================

### CatBoost 전처리
- CB 피처: 65개, 카테고리: 10개
- 카테고리: ['시술 시기 코드', '시술 당시 나이', '시술 유형', '특정 시술 유형', '배란 유도 유형', '배아 생성 주요 이유', '난자 출처', '정자 출처', '난자 기증자 나이', '정자 기증자 나이']

### CatBoost 3-seed 앙상블 (seed=[42, 2026, 2604])
### 파라미터: iterations=5000, lr=0.01, depth=8, l2=3

  --- Seed 42 (1/3) ---
    Fold 1: AUC=0.7383, iter=1647, 소요=1.3분
    Fold 2: AUC=0.7427, iter=1620, 소요=1.3분
    Fold 3: AUC=0.7402, iter=1835, 소요=1.4분
    Fold 4: AUC=0.7383, iter=1263, 소요=1.0분
    Fold 5: AUC=0.7408, iter=1463, 소요=1.2분
  Seed 42 OOF AUC: 0.7401

  --- Seed 2026 (2/3) ---
    Fold 1: AUC=0.7367, iter=2174, 소요=1.7분
    Fold 2: AUC=0.7403, iter=1664, 소요=1.3분
    Fold 3: AUC=0.7375, iter=1494, 소요=1.2분
    Fold 4: AUC=0.7468, iter=1791, 소요=1.4분
    Fold 5: AUC=0.7390, iter=1719, 소요=1.4분
  Seed 2026 OOF AUC: 0.7401

  --- Seed 2604 (3/3) ---
    Fold 1: AUC=0.7402, iter=1807, 소요=1.5분
    Fold 2: AUC=0.7380, iter=1406, 소요=1.1분
    Fold 3: AUC=0.7415, iter=1618, 소요=1.3분
    Fold 4: AUC=0.7381, iter=1713, 소요=1.3분
    Fold 5: AUC=0.7421, iter=1555, 소요=1.3분
  Seed 2604 OOF AUC: 0.7399

  === CatBoost 3-seed OOF AUC: 0.7403 ===
  seed별: ['0.7401', '0.7401', '0.7399']

============================================================
## PIPELINE B: XGBoost (팀원 스타일 전처리)
============================================================

### XGBoost 전처리 (팀원 스타일)
- 파생변수: 40개
- 범주형 인코딩: 20개
- XGB 피처: 94개

### XGBoost 5-Fold (팀원 파라미터: depth=5, lr=0.02)
### 파라미터: depth=5, lr=0.02, n_est=3000, min_child=3

  [XGB] Fold 1/5 학습 중...
  [XGB] Fold 1: AUC=0.7382, iter=760, 소요=0.1분

  [XGB] Fold 2/5 학습 중...
  [XGB] Fold 2: AUC=0.7428, iter=994, 소요=0.1분

  [XGB] Fold 3/5 학습 중...
  [XGB] Fold 3: AUC=0.7403, iter=615, 소요=0.1분

  [XGB] Fold 4/5 학습 중...
  [XGB] Fold 4: AUC=0.7382, iter=582, 소요=0.1분

  [XGB] Fold 5/5 학습 중...
  [XGB] Fold 5: AUC=0.7407, iter=746, 소요=0.1분

  === XGBoost OOF AUC: 0.7400 ===

============================================================
## [7] 크로스 블렌딩 (CB 3seed × 팀원 XGB)
============================================================
  최적: XGB=0.41, CB=0.59, AUC=0.7405
  → 블렌딩 선택 (AUC=0.7405)
    CB 단독: 0.7403
    XGB 단독: 0.7400
    블렌딩: 0.7405 ★

## [8] 종합 평가지표

### 확률 기반 지표
  OOF AUC:      0.740547
  OOF Log Loss: 0.487538
  OOF AP:       0.451620

### Threshold별 분류 지표
   Threshold   Accuracy  Precision     Recall         F1 Specificity
  -----------------------------------------------------------------
        0.20     0.5521     0.3554     0.9011     0.5097     0.4305
        0.25     0.6124     0.3815     0.8057     0.5179     0.5451
        0.30     0.6651     0.4103     0.6774     0.5110     0.6608
        0.35     0.7058     0.4421     0.5301     0.4821     0.7670
        0.40     0.7309     0.4741     0.3797     0.4217     0.8532
        0.45     0.7425     0.5035     0.2490     0.3332     0.9145
        0.50     0.7466     0.5451     0.1168     0.1923     0.9660

  최적 F1: 0.5179 (threshold=0.25)

### 개별 모델 비교
               모델        AUC    LogLoss         AP
  --------------------------------------------------
         CB 3seed     0.7403     0.4878     0.4514
           XGB 팀원     0.7400     0.4877     0.4507
               최종     0.7405     0.4875     0.4516

  CB↔XGB OOF 상관계수: 0.9938
  (낮을수록 블렌딩 효과 큼, 0.95 이하가 이상적)

## [9] 제출 파일
- 파일: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\sample_submission_v11_20260316_133331.csv
- 확률: mean=0.2584, std=0.1593, min=0.0002, max=0.7619
- 예시:
        ID  probability
TEST_00000     0.001100
TEST_00001     0.007789
TEST_00002     0.154250
TEST_00003     0.110128
TEST_00004     0.498678

## [10] 피처 중요도

### XGBoost 상위 30 (팀원 스타일)
  1. 이식배아수_구간: 0.1432
  2. 이식된 배아 수: 0.1336
  3. 시술 유형: 0.0941
  4. 배아 이식 경과일: 0.0664
  5. 저장된 배아 수: 0.0513
  6. 초고령_여부: 0.0409
  7. 난자 채취 경과일: 0.0327
  8. 배아이식비율: 0.0266
  9. 시술 당시 나이_num: 0.0244
  10. 나이_제곱: 0.0215
  11. 복합위험도점수: 0.0198
  12. 나이_임상구간: 0.0187
  13. 신선 배아 사용 여부: 0.0186
  14. 난자 출처: 0.0179
  15. 극고령_여부: 0.0175
  16. 총 생성 배아 수: 0.0169
  17. 단일 배아 이식 여부: 0.0148
  18. 배아저장비율: 0.0136
  19. 난자 기증자 나이_num: 0.0112
  20. 난자대비이식배아수: 0.0111
  21. 수집된 신선 난자 수: 0.0066
  22. 정자 출처: 0.0055
  23. 배란 자극 여부: 0.0053
  24. IVF임신률: 0.0051
  25. 배아 해동 경과일: 0.0051
  26. PGS 시술 여부: 0.0045
  27. 전체임신률: 0.0044
  28. 불임 원인 - 난관 질환: 0.0044
  29. DI 출산 횟수_num: 0.0044
  30. 배아 생성 주요 이유: 0.0044

### CatBoost 상위 30 (피처 축소)
  1. 실제이식여부: 25.13
  2. total_embryo_ratio: 12.42
  3. 이식된 배아 수: 7.54
  4. 시술 당시 나이 [cat]: 6.26
  5. 배아 이식 경과일: 5.48
  6. 수집된 신선 난자 수: 4.35
  7. ivf_transfer_ratio: 3.76
  8. 저장된 배아 수: 3.42
  9. ivf_storage_ratio: 3.28
  10. 배아_이용률: 2.81
  11. 배아_잉여율: 2.60
  12. 정자 출처 [cat]: 2.38
  13. 난자 출처 [cat]: 1.93
  14. 총 생성 배아 수: 1.62
  15. 시술 시기 코드 [cat]: 1.38
  16. 배아 생성 주요 이유 [cat]: 1.23
  17. 난자_배아_전환율: 1.05
  18. 수정_성공률: 0.93
  19. IVF 시술 횟수: 0.86
  20. 클리닉 내 총 시술 횟수: 0.83
  21. 배란 유도 유형 [cat]: 0.71
  22. 특정 시술 유형 [cat]: 0.62
  23. 총 임신 횟수: 0.62
  24. 정자 기증자 나이 [cat]: 0.60
  25. 배란 자극 여부: 0.57
  26. 난자 기증자 나이 [cat]: 0.54
  27. 불임 원인 - 남성 요인: 0.51
  28. 신선 배아 사용 여부: 0.50
  29. 해동된 배아 수: 0.50
  30. 총 시술 횟수: 0.45

## [11] 버전 비교
| 버전 | 모델 | OOF AUC | LogLoss | AP | 비고 |
|------|------|---------|---------|------|------|
| v1 | CB원본 | 0.7403 | - | - | 베이스라인 |
| v8 | XGB+CB | 0.7401 | - | - | +파생변수 |
| v9 | XGB+CB 3seed | 0.7405 | - | - | +IVF/DI분기 |
| v10 | XGB+CB 3seed | 0.7403 | 0.4878 | 0.4514 | +의료파생(과다) |
| v11-CB | CB 3seed | 0.7403 | 0.4878 | 0.4514 | 피처축소 |
| v11-XGB | XGB 팀원 | 0.7400 | 0.4877 | 0.4507 | 팀원파이프라인 |
| v11 | 블렌딩 | 0.7405 | 0.4875 | 0.4516 | 최종 |

============================================================
## 최종 요약
============================================================
- v11 핵심 전략:
  1. CatBoost: 피처 축소 (95→65개), 원본 카테고리 유지
  2. XGBoost: 팀원 파이프라인 재현 (factorize + 의료 파생)
  3. 서로 다른 전처리 파이프라인으로 크로스 블렌딩
- CB 3-seed: 0.7403 (seed별: ['0.7401', '0.7401', '0.7399'])
- XGB 팀원: 0.7400
- CB↔XGB 상관: 0.9938
- 블렌딩: XGB=0.41, CB=0.59
- **최종: 블렌딩, OOF AUC=0.7405** (v9 대비 +0.0000)
- OOF LogLoss: 0.4875, AP: 0.4516
- 최적 F1: 0.5179 (th=0.25)
- 소요: 20.2분
- 로그: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\log_v11.md
============================================================
