# v12 - CB 3seed + XGB 팀원 + TabNet → 3모델 블렌딩
시각: 20260316_142354
============================================================

## [1] 데이터 로드
- train: (256351, 69), test: (90067, 68)
- 타겟: 0=190123, 1=66228, 양성비율=25.8%

============================================================
## PIPELINE A: CatBoost (피처 축소, 원본 카테고리)
============================================================

### CatBoost 전처리
- CB 피처: 65개, 카테고리: 10개

### CatBoost 3-seed 앙상블 (seed=[42, 2026, 2604])
### 파라미터: iterations=5000, lr=0.01, depth=8, l2=3

  --- Seed 42 (1/3) ---
    Fold 1: AUC=0.7383, iter=1647, 소요=1.3분
    Fold 2: AUC=0.7427, iter=1620, 소요=1.3분
    Fold 3: AUC=0.7403, iter=2015, 소요=1.6분
    Fold 4: AUC=0.7383, iter=1428, 소요=1.2분
    Fold 5: AUC=0.7408, iter=1463, 소요=1.2분
  Seed 42 OOF AUC: 0.7401

  --- Seed 2026 (2/3) ---
    Fold 1: AUC=0.7367, iter=2174, 소요=1.7분
    Fold 2: AUC=0.7403, iter=1568, 소요=1.3분
    Fold 3: AUC=0.7375, iter=1510, 소요=1.2분
    Fold 4: AUC=0.7468, iter=1684, 소요=1.4분
    Fold 5: AUC=0.7390, iter=1443, 소요=1.2분
  Seed 2026 OOF AUC: 0.7400

  --- Seed 2604 (3/3) ---
    Fold 1: AUC=0.7402, iter=1765, 소요=1.4분
    Fold 2: AUC=0.7380, iter=1406, 소요=1.1분
    Fold 3: AUC=0.7415, iter=1618, 소요=1.3분
    Fold 4: AUC=0.7381, iter=1706, 소요=1.3분
    Fold 5: AUC=0.7421, iter=1565, 소요=1.2분
  Seed 2604 OOF AUC: 0.7399

  === CatBoost 3-seed OOF AUC: 0.7403 ===

============================================================
## PIPELINE B: XGBoost (팀원 스타일)
============================================================

### XGBoost 전처리
- XGB 피처: 93개

### XGBoost 5-Fold (depth=5, lr=0.02)

  [XGB] Fold 1/5 학습 중...
  [XGB] Fold 1: AUC=0.7382, iter=729, 소요=0.1분

  [XGB] Fold 2/5 학습 중...
  [XGB] Fold 2: AUC=0.7430, iter=1036, 소요=0.1분

  [XGB] Fold 3/5 학습 중...
  [XGB] Fold 3: AUC=0.7404, iter=664, 소요=0.1분

  [XGB] Fold 4/5 학습 중...
  [XGB] Fold 4: AUC=0.7381, iter=635, 소요=0.1분

  [XGB] Fold 5/5 학습 중...
  [XGB] Fold 5: AUC=0.7407, iter=720, 소요=0.1분

  === XGBoost OOF AUC: 0.7401 ===

============================================================
## PIPELINE C: TabNet (신경망 기반)
============================================================

### TabNet 전처리 (XGB 피처 + 스케일링)
- TabNet 피처: 93개

### TabNet 5-Fold 학습
### 파라미터: n_d=32, n_a=32, n_steps=5, gamma=1.5, lr=0.02

  [TabNet] Fold 1/5 학습 중...

Early stopping occurred at epoch 83 with best_epoch = 53 and best_val_0_auc = 0.735
  [TabNet] Fold 1: AUC=0.7350, 소요=12.4분

  [TabNet] Fold 2/5 학습 중...

Early stopping occurred at epoch 85 with best_epoch = 55 and best_val_0_auc = 0.74016
  [TabNet] Fold 2: AUC=0.7402, 소요=12.7분

  [TabNet] Fold 3/5 학습 중...

Early stopping occurred at epoch 63 with best_epoch = 33 and best_val_0_auc = 0.73722
  [TabNet] Fold 3: AUC=0.7372, 소요=9.5분

  [TabNet] Fold 4/5 학습 중...

Early stopping occurred at epoch 64 with best_epoch = 34 and best_val_0_auc = 0.73313
  [TabNet] Fold 4: AUC=0.7331, 소요=9.5분

  [TabNet] Fold 5/5 학습 중...

Early stopping occurred at epoch 76 with best_epoch = 46 and best_val_0_auc = 0.73837
  [TabNet] Fold 5: AUC=0.7384, 소요=11.4분

  === TabNet OOF AUC: 0.7367 ===

============================================================
## [7] 3모델 블렌딩
============================================================

### OOF 상관계수
  CB ↔ XGB:    0.9938
  CB ↔ TabNet:  0.9786
  XGB ↔ TabNet: 0.9797

### 가중치 그리드 탐색
  최적: CB=0.53, XGB=0.37, TabNet=0.1
  블렌딩 AUC: 0.7406

### 후보 비교:
  CB 단독: 0.7403
  XGB 단독: 0.7401
  TabNet 단독: 0.7367
  CB+XGB: 0.7406
  3모델 블렌딩: 0.7406 ★

  → 3모델 블렌딩 선택 (AUC=0.7406)

## [8] 종합 평가지표

### 확률 기반 지표
  OOF AUC:      0.740603
  OOF Log Loss: 0.487492
  OOF AP:       0.451628

### Threshold별 분류 지표
   Threshold   Accuracy  Precision     Recall         F1 Specificity
  -----------------------------------------------------------------
        0.20     0.5515     0.3551     0.9014     0.5094     0.4296
        0.25     0.6120     0.3813     0.8062     0.5177     0.5443
        0.30     0.6650     0.4101     0.6770     0.5108     0.6608
        0.35     0.7060     0.4423     0.5289     0.4817     0.7677
        0.40     0.7310     0.4742     0.3797     0.4217     0.8533
        0.45     0.7426     0.5038     0.2494     0.3336     0.9145
        0.50     0.7464     0.5430     0.1156     0.1907     0.9661

  최적 F1: 0.5177 (threshold=0.25)

### 개별 모델 비교
               모델        AUC    LogLoss         AP
  --------------------------------------------------
         CB 3seed     0.7403     0.4878     0.4514
           XGB 팀원     0.7401     0.4877     0.4505
           TabNet     0.7367     0.4897     0.4464
               최종     0.7406     0.4875     0.4516

## [9] 제출 파일
- 메인: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\sample_submission_v12_20260316_142354.csv
- XGB단독: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\sample_submission_v12_xgb_only_20260316_142354.csv
- 확률: mean=0.2584, std=0.1592
- 예시:
        ID  probability
TEST_00000     0.001099
TEST_00001     0.007232
TEST_00002     0.155109
TEST_00003     0.110429
TEST_00004     0.501081

## [10] 피처 중요도

### XGBoost 상위 20
  1. 이식배아수_구간: 0.1425
  2. 이식된 배아 수: 0.1303
  3. 시술 유형: 0.0825
  4. 배아 이식 경과일: 0.0686
  5. 저장된 배아 수: 0.0356
  6. 난자대비이식배아수: 0.0304
  7. 배아이식비율: 0.0283
  8. 나이_제곱: 0.0266
  9. 난자 채취 경과일: 0.0249
  10. 시술 당시 나이_num: 0.0247
  11. 복합위험도점수: 0.0209
  12. 초고령_여부: 0.0208
  13. 난자 출처: 0.0202
  14. 총 생성 배아 수: 0.0180
  15. 동결 배아 사용 여부: 0.0178
  16. 배아저장비율: 0.0168
  17. 나이_임상구간: 0.0164
  18. 고령_여부: 0.0144
  19. 극고령_여부: 0.0139
  20. 단일 배아 이식 여부: 0.0135

### CatBoost 상위 20
  1. 실제이식여부: 26.67
  2. total_embryo_ratio: 10.59
  3. 이식된 배아 수: 7.84
  4. 시술 당시 나이 [cat]: 6.36
  5. 배아 이식 경과일: 5.33
  6. 수집된 신선 난자 수: 4.38
  7. ivf_transfer_ratio: 3.70
  8. 저장된 배아 수: 3.39
  9. ivf_storage_ratio: 3.21
  10. 배아_이용률: 2.80
  11. 배아_잉여율: 2.70
  12. 난자 출처 [cat]: 1.91
  13. 정자 출처 [cat]: 1.89
  14. 시술 시기 코드 [cat]: 1.62
  15. 총 생성 배아 수: 1.59
  16. 배아 생성 주요 이유 [cat]: 1.34
  17. 수정_성공률: 1.03
  18. 난자_배아_전환율: 0.99
  19. IVF 시술 횟수: 0.89
  20. 배란 유도 유형 [cat]: 0.85

### TabNet Feature Importance 상위 20
  1. 이식된 배아 수: 0.2687
  2. 시술 당시 나이_num: 0.1083
  3. 배아 이식 경과일: 0.0776
  4. 이식배아수_구간: 0.0527
  5. 파트너 정자와 혼합된 난자 수: 0.0414
  6. 저장된 배아 수: 0.0404
  7. 배란 유도 유형: 0.0296
  8. 신선 배아 사용 여부: 0.0288
  9. 나이_임상구간: 0.0262
  10. 착상 전 유전 진단 사용 여부: 0.0209
  11. 나이_제곱: 0.0208
  12. 총 생성 배아 수: 0.0192
  13. IVF실패횟수: 0.0169
  14. 배아생성효율: 0.0155
  15. 단일 배아 이식 여부: 0.0147
  16. 임신경험있음: 0.0135
  17. IVF임신률: 0.0134
  18. 저장된 신선 난자 수: 0.0131
  19. 배아이식비율: 0.0129
  20. 착상 전 유전 검사 사용 여부: 0.0117

## [11] 버전 비교
| 버전 | 모델 | OOF AUC | LogLoss | AP | 비고 |
|------|------|---------|---------|------|------|
| v1 | CB원본 | 0.7403 | - | - | 베이스라인 |
| v9 | XGB+CB 3seed | 0.7405 | - | - | +IVF/DI분기 |
| v11 | CB+XGB 크로스 | 0.7405 | 0.4875 | 0.4516 | 팀원XGB |
| v12-CB | CB 3seed | 0.7403 | 0.4878 | 0.4514 | 피처축소 |
| v12-XGB | XGB 팀원 | 0.7401 | 0.4877 | 0.4505 | depth=5 |
| v12-Tab | TabNet | 0.7367 | 0.4897 | 0.4464 | 신경망 |
| v12 | 3모델 블렌딩 | 0.7406 | 0.4875 | 0.4516 | 최종 |

============================================================
## 최종 요약
============================================================
- v12 핵심: CatBoost + XGBoost + TabNet 3모델 블렌딩
- CatBoost 3-seed: 0.7403
- XGBoost 팀원: 0.7401
- TabNet: 0.7367
- OOF 상관: CB↔XGB=0.9938, CB↔Tab=0.9786, XGB↔Tab=0.9797
- 블렌딩: CB=0.53, XGB=0.37, Tab=0.1
- **최종: 3모델 블렌딩, OOF AUC=0.7406** (v11 대비 +0.0001)
- OOF LogLoss: 0.4875, AP: 0.4516
- 최적 F1: 0.5177 (th=0.25)
- XGB 단독 제출 파일도 생성 (test 일반화 확인용)
- 소요: 76.0분
- 로그: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\log_v12.md
============================================================
