# ensemble_v20_team
시각: 20260318_213112
======================================================================

## [1] 데이터 로드
- train: (256351, 69)
- sample_submission: (90067, 2)
- target 0=190123, 1=66228, pos=25.83%

## [2] 예측 파일 로드
- v20 OOF: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\oof_v20_pruned_final.npy
- v20 TEST: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\test_v20_pruned_final.npy
  v20 OOF AUC=0.740810
- XGB OOF: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\team_output\xgb_v2_reg_relax_oof_predictions.csv
  shape=(256351, 5), pred_col=oof_pred_prob, id_col=ID, auc=0.740113
- XGB SUB: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\team_output\xgb_v2_reg_relax_submission.csv
  shape=(90067, 2), pred_col=임신 성공 여부, id_col=ID
- LGB OOF: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\team_output\lightgbm_v1_lightgbm_baseline_v1_oof_predictions.csv
  shape=(256351, 5), pred_col=oof_pred_prob, id_col=ID, auc=0.739865
- LGB SUB: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\team_output\lightgbm_v1_lightgbm_baseline_v1_submission.csv
  shape=(90067, 2), pred_col=임신 성공 여부, id_col=ID

## [3] OOF 상관 분석
- OOF Pearson correlation
  v20: v20=1.0000, xgb=0.9937, lgb=0.9934
  xgb: v20=0.9937, xgb=1.0000, lgb=0.9959
  lgb: v20=0.9934, xgb=0.9959, lgb=1.0000
- 저장: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\corr_ensemble_v20_team_20260318_213112.csv

## [4] 앙상블 탐색 시작

### [prob] blend 탐색 시작
  subset=['v20', 'xgb'] | AUC=0.740898 | LogLoss=0.490527 | AP=0.452094 | weights={'v20': 0.73, 'xgb': 0.27}
  subset=['v20', 'lgb'] | AUC=0.740870 | LogLoss=0.490971 | AP=0.452109 | weights={'v20': 0.78, 'lgb': 0.22}
  subset=['xgb', 'lgb'] | AUC=0.740252 | LogLoss=0.487596 | AP=0.450739 | weights={'xgb': 0.63, 'lgb': 0.37}
  subset=['v20', 'xgb', 'lgb'] | AUC=0.740902 | LogLoss=0.490352 | AP=0.452105 | weights={'v20': 0.71, 'xgb': 0.21, 'lgb': 0.08}

### [rank] blend 탐색 시작
  subset=['v20', 'xgb'] | AUC=0.740899 | LogLoss=0.717625 | AP=0.452084 | weights={'v20': 0.74, 'xgb': 0.26}
  subset=['v20', 'lgb'] | AUC=0.740873 | LogLoss=0.717567 | AP=0.452091 | weights={'v20': 0.8, 'lgb': 0.2}
  subset=['xgb', 'lgb'] | AUC=0.740254 | LogLoss=0.718543 | AP=0.450795 | weights={'xgb': 0.64, 'lgb': 0.36}
  subset=['v20', 'xgb', 'lgb'] | AUC=0.740904 | LogLoss=0.717416 | AP=0.452087 | weights={'v20': 0.73, 'xgb': 0.2, 'lgb': 0.07}

- 탐색 소요: 1.60분

## [5] 결과 저장
- 탐색 결과 저장: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\ensemble_search_ensemble_v20_team_20260318_213112.csv
- best config 저장: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\best_ensemble_v20_team_20260318_213112.json
- OOF npy 저장: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\oof_ensemble_v20_team_20260318_213112.npy
- TEST npy 저장: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\test_ensemble_v20_team_20260318_213112.npy
- submission 저장: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\submission_ensemble_v20_team_20260318_213112.csv

## [6] 상위 결과 Top 20
 1. mode=rank   | subset=v20 + xgb + lgb                | AUC=0.740904 | LogLoss=0.717416 | AP=0.452087 | weights={'v20': 0.73, 'xgb': 0.2, 'lgb': 0.07}
 2. mode=prob   | subset=v20 + xgb + lgb                | AUC=0.740902 | LogLoss=0.490352 | AP=0.452105 | weights={'v20': 0.71, 'xgb': 0.21, 'lgb': 0.08}
 3. mode=rank   | subset=v20 + xgb                      | AUC=0.740899 | LogLoss=0.717625 | AP=0.452084 | weights={'v20': 0.74, 'xgb': 0.26}
 4. mode=prob   | subset=v20 + xgb                      | AUC=0.740898 | LogLoss=0.490527 | AP=0.452094 | weights={'v20': 0.73, 'xgb': 0.27}
 5. mode=rank   | subset=v20 + lgb                      | AUC=0.740873 | LogLoss=0.717567 | AP=0.452091 | weights={'v20': 0.8, 'lgb': 0.2}
 6. mode=prob   | subset=v20 + lgb                      | AUC=0.740870 | LogLoss=0.490971 | AP=0.452109 | weights={'v20': 0.78, 'lgb': 0.22}
 7. mode=single | subset=v20                            | AUC=0.740810 | LogLoss=0.493269 | AP=0.452123 | weights={'v20': 1.0}
 8. mode=rank   | subset=xgb + lgb                      | AUC=0.740254 | LogLoss=0.718543 | AP=0.450795 | weights={'xgb': 0.64, 'lgb': 0.36}
 9. mode=prob   | subset=xgb + lgb                      | AUC=0.740252 | LogLoss=0.487596 | AP=0.450739 | weights={'xgb': 0.63, 'lgb': 0.37}
10. mode=single | subset=xgb                            | AUC=0.740113 | LogLoss=0.487687 | AP=0.450544 | weights={'xgb': 1.0}
11. mode=single | subset=lgb                            | AUC=0.739865 | LogLoss=0.487778 | AP=0.450005 | weights={'lgb': 1.0}

======================================================================
## 최종 요약
======================================================================
- best mode:   rank
- best subset: v20 + xgb + lgb
- best weights: {'v20': 0.73, 'xgb': 0.2, 'lgb': 0.07}
- best OOF AUC:     0.740904
- best OOF LogLoss: 0.717416
- best OOF AP:      0.452087
- submission: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\submission_ensemble_v20_team_20260318_213112.csv
- 총 소요: 1.62분
======================================================================