# v8 - Age U-Curve + Purpose Zero + Embryo Ratio + CB파생 + XGB depth조정
시각: 20260315_213000
============================================================

## [1] 데이터 로드
- train: (256351, 69), test: (90067, 68)
- 타겟: 0=190123, 1=66228, 양성비율=25.8%

## [3] XGBoost 전처리
  [train] step1: (256351, 63), obj=20
  [train] step2: obj=10
  [train] step3: obj=7
  [train] step4: obj=4
  [train] step5: obj=4
  [train] step6: 컬럼=80, obj=4
  [test] step1: (90067, 63), obj=20
  [test] step2: obj=10
  [test] step3: obj=7
  [test] step4: obj=4
  [test] step5: obj=4
  [test] step6: 컬럼=80, obj=4

## [4] Target Encoding (K-Fold)
  - 특정 시술 유형 (고유값: 24) → 덮어쓰기
  - 배아 생성 주요 이유 (고유값: 14) → 덮어쓰기
  - 시술 시기 코드 (고유값: 7) → 덮어쓰기
  - 배란 유도 유형 (고유값: 4) → 덮어쓰기
  - 시술 당시 나이 (고유값: 7) → 시술 당시 나이_te

## [5] XGBoost 피처 정리
- 피처 수: 74
- v8 신규: age_u_curve, age_peak, purpose_zero, total_embryo_ratio

## [6] CatBoost 데이터 (네이티브 카테고리 + 파생변수)
- CB 피처: 65개, 카테고리: 20개
- CB 파생변수: 수정_성공률, 배아_이용률, 배아_잉여율, 난자_배아_전환율,
              실제이식여부, total_embryo_ratio, purpose_zero, age_u_curve, age_peak

## [7] 5-Fold: XGBoost(depth=7) + CatBoost(GPU 네이티브)

### XGBoost: depth=7, 피처=74
### CatBoost: depth=8, 피처=65, cat=20

  ===== Fold 1/5 =====
    [XGB] 학습 중...
    [XGB] AUC: 0.7366, iter: 1153
    [CB] 학습 중...
    [CB] AUC: 0.7381, iter: 1549
    소요: 1.7분

  ===== Fold 2/5 =====
    [XGB] 학습 중...
    [XGB] AUC: 0.7423, iter: 1080
    [CB] 학습 중...
    [CB] AUC: 0.7427, iter: 2423
    소요: 2.5분

  ===== Fold 3/5 =====
    [XGB] 학습 중...
    [XGB] AUC: 0.7394, iter: 664
    [CB] 학습 중...
    [CB] AUC: 0.7402, iter: 2306
    소요: 2.4분

  ===== Fold 4/5 =====
    [XGB] 학습 중...
    [XGB] AUC: 0.7381, iter: 769
    [CB] 학습 중...
    [CB] AUC: 0.7380, iter: 1471
    소요: 1.6분

  ===== Fold 5/5 =====
    [XGB] 학습 중...
    [XGB] AUC: 0.7395, iter: 834
    [CB] 학습 중...
    [CB] AUC: 0.7408, iter: 1867
    소요: 2.0분

  === 개별 OOF AUC ===
    XGBoost:  0.7391
    CatBoost: 0.7399

## [8] 블렌딩 가중치 탐색
  1차: XGB=0.3, CB=0.7, AUC=0.7401
  최종: XGB=0.31, CB=0.69, AUC=0.7401

## [9] 제출 파일
- 파일: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\sample_submission_v8_20260315_213000.csv
- 확률: mean=0.2583, std=0.1592, min=0.0005, max=0.7505
- 예시:
        ID  probability
TEST_00000     0.001689
TEST_00001     0.009378
TEST_00002     0.152706
TEST_00003     0.106100
TEST_00004     0.512310

## [10] 피처 중요도

### XGBoost 상위 25
  1. 실제이식여부: 0.4879
  2. total_embryo_ratio ★v8: 0.0754
  3. 시술 유형: 0.0663
  4. 난자 출처: 0.0426
  5. 저장된 배아 수: 0.0346
  6. 신선 배아 사용 여부: 0.0304
  7. 배아 이식 경과일: 0.0216
  8. 시술 당시 나이: 0.0181
  9. 이식된 배아 수: 0.0153
  10. 배아_잉여율: 0.0153
  11. 이식유형_복수신선: 0.0138
  12. purpose_zero ★v8: 0.0101
  13. is_donor_egg: 0.0094
  14. 총 생성 배아 수: 0.0088
  15. 난자 기증자 나이: 0.0084
  16. 배아_이용률: 0.0083
  17. 정자 출처: 0.0077
  18. 시술 당시 나이_te: 0.0051
  19. 동결 배아 사용 여부: 0.0050
  20. age_peak ★v8: 0.0042
  21. 이식유형_단일동결: 0.0039
  22. 총 출산 횟수: 0.0033
  23. 단일 배아 이식 여부: 0.0032
  24. IVF 임신 횟수: 0.0031
  25. 미세주입 후 저장된 배아 수: 0.0031

### CatBoost 상위 25
  1. 실제이식여부: 18.82
  2. total_embryo_ratio ★v8: 17.65
  3. 이식된 배아 수: 8.30
  4. 수집된 신선 난자 수: 6.60
  5. 배아 이식 경과일: 6.49
  6. 시술 당시 나이: 4.68
  7. 저장된 배아 수: 4.31
  8. 배아_이용률: 3.83
  9. 배아_잉여율: 2.79
  10. 난자 출처: 2.12
  11. 총 생성 배아 수: 1.73
  12. 정자 출처: 1.58
  13. 시술 시기 코드: 1.31
  14. 수정_성공률: 1.12
  15. 혼합된 난자 수: 1.06
  16. IVF 시술 횟수: 1.01
  17. purpose_zero ★v8: 1.00
  18. 난자_배아_전환율: 0.91
  19. 배아 생성 주요 이유: 0.89
  20. age_peak ★v8: 0.84
  21. 클리닉 내 총 시술 횟수: 0.82
  22. 미세주입된 난자 수: 0.81
  23. 신선 배아 사용 여부: 0.71
  24. 특정 시술 유형: 0.70
  25. 해동된 배아 수: 0.69

## [11] 버전 비교

| 버전 | 모델 | OOF AUC | 비고 |
|------|------|---------|------|
| v1 | CB원본 | 0.7403 | 베이스라인 |
| v4 | XGB | 0.7392 | 컬럼복원 |
| v7 | XGB+CB | 0.7402 | 블렌딩 |
| v8 | XGB+CB | 0.7401 | U-curve+Purpose+Ratio |
| v8-XGB | XGB | 0.7391 | depth=7 |
| v8-CB | CB | 0.7399 | +파생변수 |

============================================================
## 최종 요약
============================================================
- XGB OOF AUC: 0.7391 (depth=7, 피처=74)
- CB OOF AUC:  0.7399 (네이티브cat+파생, 피처=65)
- 블렌딩: XGB=0.31, CB=0.69
- **최종 OOF AUC: 0.7401**
- v7 대비: -0.0001
- 소요: 10.3분
- 로그: C:\Users\ico26\oz\Infertility-Success-Classifier\suho\result\log_v8.md
============================================================
